const cards = [
  {
    "id": "5fc7b55c8f50df001bba4b81",
    "title": "SOHO's pioneering 25 years in orbit",
    "url": "https://sci.esa.int/web/soho/-/soho-s-pioneering-25-years-in-orbit",
    "imageUrl": "https://cdn.sci.esa.int/documents/33795/35391/ESA_SOHO_25suns-composite_600.jpg",
    "newsSite": "ESA",
    "summary": "The ESA-NASA Solar and Heliospheric Observatory (SOHO) is celebrating its twenty-fifth launch anniversary.",
    "publishedAt": "2020-12-02T15:40:12.000Z",
    "updatedAt": "2020-12-02T15:40:12.641Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b52c8f50df001bba4b55",
    "title": "Soyuz rocket launches Emirati military satellite after lengthy delay",
    "url": "https://spaceflightnow.com/2020/12/02/soyuz-rocket-launches-emirati-reconnaissance-satellite-after-lengthy-delay/",
    "imageUrl": "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2020/11/vs24_quick1.jpg",
    "newsSite": "Spaceflight Now",
    "summary": "After months of delays caused by launch vehicle issues and the coronavirus pandemic, a Russian Soyuz rocket and Fregat upper stage took off from South America and delivered the French-built Falcon Eye 2 military observation satellite to an on-target orbit Tuesday night for the United Arab Emirates.",
    "publishedAt": "2020-12-02T15:39:22.000Z",
    "updatedAt": "2020-12-02T15:39:25.112Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b54e8f50df001bba4b77",
    "title": "Space balloon company raises funds, will conduct first test flight next year",
    "url": "https://arstechnica.com/science/2020/12/space-balloon-company-raises-funds-will-conduct-first-test-flight-next-year/",
    "imageUrl": "https://cdn.arstechnica.net/wp-content/uploads/2020/12/Space-Perspective_Capsule_High-Alt_291019-sharp-Bahamas.jpg",
    "newsSite": "Arstechnica",
    "summary": "No ticket price has been revealed, but it likely will be on the order of $125,000.",
    "publishedAt": "2020-12-02T14:00:01.000Z",
    "updatedAt": "2020-12-02T15:39:58.944Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b53f8f50df001bba4b6d",
    "title": "Europe and Russia launch Emirati military/civilian Earth imaging satellite",
    "url": "https://www.nasaspaceflight.com/2020/12/arianespace-emirati-military-civilian-imaging-satellite/",
    "imageUrl": "https://www.nasaspaceflight.com/wp-content/uploads/2020/12/2018-11-07-02_13_35-DrXWT2PW4AAEM99.jpg-1200×851.jpg",
    "newsSite": "NASA Spaceflight",
    "summary": "Arianespace has used — with Russia’s support — a Soyuz ST-A rocket to launch a joint military and civilian Earth imaging satellite for the United Arab Emirates Armed Forces from the Guiana Space Centre near Kourou, French Guiana.",
    "publishedAt": "2020-12-01T21:58:38.000Z",
    "updatedAt": "2020-12-02T15:39:44.020Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b54f8f50df001bba4b78",
    "title": "Yes, the 2020 Atlantic hurricane season was bad—but was it really that bad?",
    "url": "https://arstechnica.com/science/2020/12/the-2020-atlantic-hurricane-season-is-finally-over-what-should-we-make-of-it/",
    "imageUrl": "https://cdn.arstechnica.net/wp-content/uploads/2020/12/noaa-storms.png",
    "newsSite": "Arstechnica",
    "summary": "The United States saw a total of 12 landfalls. Louisiana, alone, experienced five.",
    "publishedAt": "2020-12-01T20:41:04.000Z",
    "updatedAt": "2020-12-02T15:39:59.378Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b54f8f50df001bba4b79",
    "title": "Russian spaceport officials are being sacked left and right",
    "url": "https://arstechnica.com/science/2020/12/russian-spaceport-officials-are-being-sacked-left-and-right/",
    "imageUrl": "https://cdn.arstechnica.net/wp-content/uploads/2016/04/Vladimir_Putin_in_Vostochny_Cosmodrome_2015-10-14_2.jpg",
    "newsSite": "Arstechnica",
    "summary": "Dmitry Rogozin seems to be doing a good job of spreading the blame around.",
    "publishedAt": "2020-12-01T15:51:35.000Z",
    "updatedAt": "2020-12-02T15:39:59.790Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5668f50df001bba4b85",
    "title": "Students to Ask Questions to NASA Astronaut Aboard Space Station",
    "url": "http://www.nasa.gov/press-release/students-to-ask-questions-to-nasa-astronaut-aboard-space-station",
    "imageUrl": "https://www.nasa.gov/sites/default/files/thumbnails/image/iss064e004868.jpg?itok=Q6Wx5lzC",
    "newsSite": "NASA",
    "summary": "Students from across the nation will have an opportunity this week to hear from NASA astronaut Victor Glover aboard the International Space Station.",
    "publishedAt": "2020-12-01T15:40:00.000Z",
    "updatedAt": "2020-12-02T15:40:22.425Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5668f50df001bba4b86",
    "title": "NASA Highlights New Findings, Upcoming Missions at Virtual AGU Meeting",
    "url": "http://www.nasa.gov/press-release/nasa-highlights-new-findings-upcoming-missions-at-virtual-agu-meeting",
    "imageUrl": "https://www.nasa.gov/sites/default/files/thumbnails/image/pia22949.jpg?itok=Ief4KnIP",
    "newsSite": "NASA",
    "summary": "NASA and researchers from around the world will present new findings on a wide range of Earth and space science topics at the annual meeting of the American Geophysical Union (AGU), Dec. 1-17, held virtually this year.",
    "publishedAt": "2020-12-01T15:40:00.000Z",
    "updatedAt": "2020-12-02T15:40:22.819Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5678f50df001bba4b87",
    "title": "NASA Will Name Companies Selected to Collect Lunar Resources Under Artemis Program",
    "url": "http://www.nasa.gov/press-release/nasa-will-name-companies-selected-to-collect-lunar-resources-under-artemis-program",
    "imageUrl": "https://www.nasa.gov/sites/default/files/thumbnails/image/screen_shot_2020-12-01_at_2.04.57_pm.png?itok=1rpy-4QQ",
    "newsSite": "NASA",
    "summary": "NASA will hold a media teleconference Thursday, Dec. 3, at 1 p.m. EST to announce the companies it has selected to collect lunar resources as part of the Artemis program.",
    "publishedAt": "2020-12-01T15:40:00.000Z",
    "updatedAt": "2020-12-02T15:40:23.207Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5378f50df001bba4b5e",
    "title": "Space policy advice for Biden: Tone down war rhetoric, fix military acquisitions",
    "url": "https://spacenews.com/space-policy-advice-for-biden-tone-down-war-rhetoric-fix-military-acquisitions/",
    "imageUrl": "https://spacenews.com/wp-content/uploads/2020/12/47368338882_e2d2c5890a_k.jpg",
    "newsSite": "SpaceNews",
    "summary": "The Biden administration should support U.S. space activities while abandoning divisive and antagonistic rhetoric, says a new report from the Secure World Foundation.",
    "publishedAt": "2020-12-01T15:39:36.000Z",
    "updatedAt": "2020-12-02T15:39:35.987Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5388f50df001bba4b5f",
    "title": "Lockheed Martin completes production of SBIRS GEO-5 satellite to be launched in 2021",
    "url": "https://spacenews.com/lockheed-martin-completes-production-of-sbirs-geo-5-satellite-to-be-launched-in-2021/",
    "imageUrl": "https://spacenews.com/wp-content/uploads/2020/12/SBIRS_GEO-5_Acoustic_Test-copy-e1606854206264.jpg",
    "newsSite": "SpaceNews",
    "summary": "Lockheed Martin announced Dec. 2 it has competed production of the fifth satellite of the Space Based Infrared System constellation.",
    "publishedAt": "2020-12-01T15:39:36.000Z",
    "updatedAt": "2020-12-02T15:39:36.375Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5378f50df001bba4b5d",
    "title": "Stratospheric ballooning company Space Perspective raises $7 million",
    "url": "https://spacenews.com/stratospheric-ballooning-company-space-perspective-raises-7-million/",
    "imageUrl": "https://spacenews.com/wp-content/uploads/2020/06/spaceperspective-fla.jpg",
    "newsSite": "SpaceNews",
    "summary": "Space Perspective, a startup planning to offer tourists trips to the edge of space in a high-altitude balloon, has raised $7 million in a seed round that will allow the company to test its technologies.",
    "publishedAt": "2020-12-01T15:39:35.000Z",
    "updatedAt": "2020-12-02T15:39:35.586Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b52d8f50df001bba4b56",
    "title": "China lands sample return probe on moon",
    "url": "https://spaceflightnow.com/2020/12/01/china-lands-sample-return-probe-on-moon/",
    "imageUrl": "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2020/12/6785420.jpg",
    "newsSite": "Spaceflight Now",
    "summary": "A Chinese spacecraft successfully touched down on the moon Tuesday, beginning what engineers have described as the most challenging phase of the mission to drill, scoop, and seal rocks for launch back into orbit later this week and return to Earth in mid-December.",
    "publishedAt": "2020-12-01T15:39:25.000Z",
    "updatedAt": "2020-12-02T15:39:25.541Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5418f50df001bba4b6e",
    "title": "China lands on Moon after causing deep confusion by stopping broadcast",
    "url": "https://www.nasaspaceflight.com/2020/12/china-preparing-to-land-sample-return-mission-on-the-moon/",
    "imageUrl": "https://www.nasaspaceflight.com/wp-content/uploads/2020/12/change5_moon1.jpg",
    "newsSite": "NASA Spaceflight",
    "summary": "Eight days after launching from the Wenchang Spacecraft Launch Site in southern China, the nation’s Chang’e 5 mission has landed at Mons Rümker on the Moon to collect approximately 2 kg of material for near-immediate return to Earth.",
    "publishedAt": "2020-12-01T14:42:32.000Z",
    "updatedAt": "2020-12-02T15:39:45.201Z",
    "featured": false,
    "launches": [],
    "events": []
  },
  {
    "id": "5fc7b5508f50df001bba4b7a",
    "title": "China Chang’e 5 probe has safely landed on the Moon [Updated]",
    "url": "https://arstechnica.com/science/2020/12/china-likely-to-attempt-its-change-5-moon-landing-on-tuesday/",
    "imageUrl": "https://cdn.arstechnica.net/wp-content/uploads/2020/11/GettyImages-1229764932.jpg",
    "newsSite": "Arstechnica",
    "summary": "The Asian nation currently has seven spacecraft operating near or on the Moon.",
    "publishedAt": "2020-12-01T14:15:49.000Z",
    "updatedAt": "2020-12-02T15:40:00.199Z",
    "featured": false,
    "launches": [],
    "events": []
  }
]

export default cards
